const S={offers:[],total:0,page:1,lastPage:1,intelligence:null,intelligenceCoverage:null,history:[],trends:[],baselines:[],operations:[],active:localStorage.getItem('qvapay.activeOperationId'),operation:null,operationRole:'unknown',chat:[],config:null,auto:null,account:null,finance:null};
const $=id=>document.getElementById(id), esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const num=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—'; const rate=o=>Number(o?.amount)>0?Number(o.receive)/Number(o.amount):null;
const meta={'/':['OVERVIEW','Inicio'],'/market':['MARKET','Mercado'],'/auto-apply':['AUTOMATION','Auto-Apply'],'/operations':['OPERATIONS','Operaciones'],'/analytics':['INTELLIGENCE','Analytics'],'/alerts':['MONITORING','Alertas'],'/account':['ACCOUNT','Cuenta'],'/finance':['FINANCE','Finanzas'],'/settings':['SYSTEM','Configuración']};
async function api(u,o={}){const r=await fetch(u,{cache:'no-store',...o}),p=await r.json();if(!r.ok)throw Error(p?.detail?.message||p?.detail||p?.error||'Error');return p}
function toast(m,c='info'){const x=document.createElement('div');x.className='toast '+c;x.textContent=m;document.getElementById('toasts').append(x);setTimeout(()=>x.remove(),3500)}
function card(t,s,b){return '<section class="card"><div class="card-head"><div><h2>'+t+'</h2><p>'+s+'</p></div></div>'+b+'</section>'} function metric(a,b,c,i){return '<article class="metric"><div class="metric-icon">'+i+'</div><span>'+a+'</span><strong>'+b+'</strong><small>'+c+'</small></article>'}
function time(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleTimeString('es-ES')}
function best(){const a=S.offers.map(rate).filter(Number.isFinite);return a.length?num(Math.max(...a),2):'—'} function low(){const a=S.offers.map(rate).filter(Number.isFinite);return a.length?num(Math.min(...a),2):'—'}
function coinAnalysis(){const groups=new Map();S.offers.forEach(o=>{const coin=String(o.coin||'').trim()||'SIN_MONEDA',r=rate(o);if(!Number.isFinite(r))return;const g=groups.get(coin)||{coin,rates:[],sell:0,buy:0,open:0};g.rates.push(r);if(String(o.type).toLowerCase()==='sell')g.sell++;if(String(o.type).toLowerCase()==='buy')g.buy++;if(String(o.status||'open').toLowerCase()==='open')g.open++;groups.set(coin,g)});return [...groups.values()].map(g=>{const x=[...g.rates].sort((a,b)=>a-b),m=Math.floor(x.length/2),median=x.length%2?x[m]:(x[m-1]+x[m])/2;return {...g,count:x.length,min:x[0],max:x[x.length-1],median,spread:x[x.length-1]-x[0]}}).sort((a,b)=>a.coin.localeCompare(b.coin))}
function nav(){let p=location.hash.slice(1)||'/';if(!meta[p])p='/';document.getElementById('pageKicker').textContent=meta[p][0];document.getElementById('pageTitle').textContent=meta[p][1];document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+p));document.getElementById('app').innerHTML=pages[p]();if(p==='/market'){bindFilters();drawOffers()}if(p==='/auto-apply')bindAuto();if(p==='/analytics'){drawCoinRadar();drawCoinAnalysis();}if(p==='/')drawHome();if(p==='/operations')drawOperations();if(p==='/account')drawAccount();if(p==='/finance')drawFinance()}
const pages={
'/':()=>'<div class="page"><div class="hero"><div><div class="eyebrow">CONTROL CENTER</div><h1>Buenos días, <em>Scanner.</em></h1><p>Un centro de mando para observar, automatizar y entender tu mercado P2P.</p></div><button class="button primary" onclick="refreshAll()">↻ Sincronizar</button></div><div class="metrics-grid">'+metric('Ofertas',num(S.total,0),'Mercado QvaPay','◈')+metric('Tasa destacada',num(S.intelligence?.bestRate,2),'Intelligence','↗')+metric('Señales',num(S.intelligence?.opportunities?.length,0),'Snapshot','⌁')+metric('Auto-Apply',S.auto?.running?'ACTIVO':'PAUSADO','Motor','✦')+'</div><div class="grid-2">'+card('Radar del mercado','Últimas ofertas','<div id="miniOffers"></div>')+card('Automatización','Estado','<div class="automation-card"><div class="pulse '+(S.auto?.running?'on':'')+'"></div><div><b>'+(S.auto?.running?'Motor activo':'Motor pausado')+'</b><p>'+esc(S.auto?.lastMessage||'Configura tus reglas.')+'</p></div><a href="#/auto-apply">Configurar →</a></div>')+'</div>'+card('Acceso rápido','Flujo operativo','<div class="quick-grid"><a href="#/market">◈<b>Mercado</b><span>Explorar ofertas</span></a><a href="#/operations">↻<b>Operaciones</b><span>Seguimiento</span></a><a href="#/analytics">⌁<b>Analytics</b><span>Inteligencia</span></a><a href="#/alerts">◉<b>Alertas</b><span>Monitoreo</span></a></div>')+'</div>',
'/market':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">LIVE MARKET</div><h1>Mercado P2P</h1><p>Filtra, compara y aplica a ofertas desde una interfaz profesional.</p></div><button class="button primary" onclick="refreshMarket()">↻ Actualizar</button></div>'+card('Filtros','Control preciso del mercado','<form id="filters" class="market-filters"><div class="filter-primary"><label>Tipo<select id="ft"><option value="">Todos los tipos</option><option value="sell">SELL · Comprar QUSD</option><option value="buy">BUY · Vender QUSD</option></select></label><label>Moneda<select id="fc"><option value="">Todas las monedas</option></select></label><label>Ordenar por<select id="fo"><option value="updated_at">Más recientes</option><option value="best_rate">Mejor tasa</option><option value="amount">Mayor QUSD</option><option value="receive">Mayor recepción</option><option value="rating">Mejor rating</option></select></label><label>Dirección<select id="fd"><option value="desc">Descendente</option><option value="asc">Ascendente</option></select></label></div><div class="filter-range"><label><span>Monto QUSD · mínimo</span><input id="fmin" type="number" step="any" min="0" inputmode="decimal" placeholder="0.00"></label><label><span>Monto QUSD · máximo</span><input id="fmax" type="number" step="any" min="0" inputmode="decimal" placeholder="Sin límite"></label><label><span>Tasa · mínima</span><input id="frmin" type="number" step="any" min="0" inputmode="decimal" placeholder="0.00"></label><label><span>Tasa · máxima</span><input id="frmax" type="number" step="any" min="0" inputmode="decimal" placeholder="Sin límite"></label></div><div class="filter-actions"><div><span id="filterCount" class="filter-count">0 filtros activos</span><button type="button" class="button ghost filter-reset" onclick="resetFilters()">Limpiar</button></div><button type="submit" class="button primary">Aplicar filtros <span>→</span></button></div></form>')+card('Ofertas',num(S.total,0)+' resultados · página '+S.page+' / '+S.lastPage,'<div class="table-wrap"><table class="market-table"><thead><tr><th>Tipo</th><th>Moneda</th><th>Tasa</th><th>QUSD</th><th>Recibe</th><th>Disponible</th><th>Usuario</th><th>Rating</th><th></th></tr></thead><tbody id="offers"></tbody></table></div><div class="pager"><button class="button secondary" onclick="changePage(-1)">←</button><span>'+S.page+'</span><button class="button secondary" onclick="changePage(1)">→</button></div>')+'</div>',
'/auto-apply':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">AUTOMATION ENGINE</div><h1>Auto-Apply</h1><p>Reglas configurables para aplicar automáticamente a ofertas elegibles.</p></div><div class="engine-badge '+(S.auto?.running?'live':'')+'"><i></i>'+(S.auto?.running?'ACTIVO':'PAUSADO')+'</div></div><div class="grid-2"><section class="card accent-card"><div class="card-head"><div><h2>Reglas</h2><p>Controla cada condición.</p></div></div><form id="af" class="form-grid"><label>Estado<input id="ae" type="checkbox" '+(S.config?.enabled?'checked':'')+'></label><label>Tipo<select id="at"><option value="sell">Sell</option><option value="buy">Buy</option></select></label><label>Moneda<input id="ac" value="'+esc(S.config?.coin||'')+'"></label><label>Tasa mínima<input id="arm" type="number" step="any" value="'+(S.config?.rateMin??'')+'"></label><label>Tasa máxima<input id="arx" type="number" step="any" value="'+(S.config?.rateMax??'')+'"></label><label>Monto mínimo<input id="aom" type="number" step="any" value="'+(S.config?.amountMin??'')+'"></label><label>Monto máximo<input id="aox" type="number" step="any" value="'+(S.config?.amountMax??'')+'"></label><label>Límite diario<input id="adl" type="number" step="any" value="'+(S.config?.dailyMaxQusd??'')+'"></label><label>Máx. simultáneas<input id="acon" type="number" min="1" value="'+(S.config?.maxConcurrent??1)+'"></label><button class="button primary wide">Guardar reglas</button></form></section>'+card('Telemetría','Estado del runtime','<div class="telemetry"><div><span>Aplicado hoy</span><b>'+num(S.auto?.dailyAppliedQusd)+' QUSD</b></div><div><span>Escaneo</span><b>'+time(S.auto?.lastScanAt)+'</b></div><div><span>Acción</span><b>'+time(S.auto?.lastActionAt)+'</b></div><div><span>Mensaje</span><b>'+esc(S.auto?.lastMessage||'—')+'</b></div></div><div class="guard">🛡️ Kill switch · límites locales · sin pagos automáticos</div>')+'</div></div>',
'/operations':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">EXECUTION CENTER</div><h1>Operaciones</h1><p>Todas las operaciones donde tu cuenta participa como creador o contraparte.</p></div><button class="button primary" onclick="refreshOperations()">↻ Actualizar</button></div><div class="metrics-grid">'+metric('Total',num(S.operations.length,0),'Operaciones propias','◈')+metric('Acción requerida',num(operationActionCount(),0),'Pendientes de tu lado','⚡')+metric('En proceso',num(S.operations.filter(o=>['processing','paid','revision'].includes(String(o.status||'').toLowerCase())).length,0),'Processing · Paid · Revision','◉')+metric('Completadas',num(S.operations.filter(o=>String(o.status||'').toLowerCase()==='completed').length,0),'Historial cerrado','✓')+'</div>'+card('Bandeja de operaciones','La fuente de verdad es QvaPay · my=1 · agrupada por estado','<div class="operation-filters"><label>Estado<select id="ofStatus"><option value="">Todos</option><option value="revision">Revisión</option><option value="processing">Procesando</option><option value="paid">Pagada</option><option value="open">Abierta</option><option value="completed">Completada</option><option value="cancelled">Cancelada</option></select></label><label>Tipo<select id="ofType"><option value="">Todos</option><option value="sell">SELL</option><option value="buy">BUY</option></select></label><label>Moneda<input id="ofCoin" placeholder="Ej. BANK_CUP"></label></div><div id="operationsList" class="operations-list"></div>')+(S.operation?card('Detalle de operación','Acciones disponibles según tu rol y el estado actual','<div id="operationDetail"></div>'):'')+'</div>',
'/analytics':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">MARKET INTELLIGENCE</div><h1>Analytics</h1><p>Análisis independiente por moneda, sin mezclar tasas ni oportunidades.</p></div><button class="button primary" onclick="refreshAll()">↻ Recalcular</button></div><div class="metrics-grid">'+metric('Muestras analizadas',num(S.intelligence?.sampleSize??S.offers.length,0),'Snapshot paginado','◌')+metric('Muestras válidas',num(S.intelligence?.validRates,0),'Tasas calculables','✓')+metric('Monedas',num(S.intelligence?.byCoin?.length??0,0),'Análisis independientes','◇')+metric('Radar activo',num((S.intelligence?.byCoin||[]).reduce((n,g)=>n+g.opportunities.length,0),0),'Señales por moneda','⌁')+'</div>'+card('Radar de oportunidades por moneda','Cada moneda tiene su propio ranking y contexto de tasa','<div id="coinRadar" class="coin-radar-list"></div>')+card('Análisis por monedas','Estadísticas independientes por moneda · sin tasas mezcladas','<div id="coinAnalysis" class="coin-analysis-list"></div>')+card('Histórico','Observaciones persistidas por moneda y tipo','<div id="historySummary">'+historySummary()+'</div><div class="trend-list">'+trendSummary()+'</div>')+'</div>'+card('Metodología','Sin inventar señales','<div class="method"><div><b>1. Cobertura</b><span>El backend recorre las páginas disponibles del listado P2P.</span></div><div><b>2. Separación</b><span>Cada moneda calcula sus propias tasas, medianas y oportunidades.</span></div><div><b>3. Decisión</b><span>Las reglas de Auto-Apply permanecen separadas del análisis.</span></div></div>')+'</div>',
'/alerts':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">MONITORING</div><h1>Alertas</h1><p>Eventos que requieren atención.</p></div></div><div class="alert-list"><div class="alert-item info"><span>◉</span><div><b>Mercado conectado</b><p>Consulta protegida mediante backend.</p></div><time>Ahora</time></div><div class="alert-item '+(S.auto?.running?'success':'neutral')+'"><span>✦</span><div><b>Auto-Apply '+(S.auto?.running?'activo':'pausado')+'</b><p>'+esc(S.auto?.lastMessage||'Sin eventos.')+'</p></div><time>'+time(S.auto?.lastActionAt)+'</time></div></div></div>',
'/account':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">ACCOUNT</div><h1>Cuenta</h1><p>Balance actual e identidad observada desde las credenciales de la aplicación.</p></div><button class="button primary" onclick="refreshAccount()">↻ Actualizar</button></div><div class="metrics-grid">'+metric('Balance',S.account?.balanceUsd==null?'—':num(S.account.balanceUsd,2)+' USD','/v2/balance','◉')+metric('Usuario',esc(S.account?.user?.username||'—'),'P2P propio','◎')+metric('KYC',S.account?.user?.kyc?'VERIFICADO':'—','Perfil','✓')+metric('VIP',S.account?.user?.vip?'ACTIVO':'—','Perfil','◆')+'</div>'+card('Identidad conectada','Campos disponibles en las ofertas propias','<div class="account-grid"><div><span>Usuario</span><b>'+esc(S.account?.user?.username||'—')+'</b></div><div><span>Nombre</span><b>'+esc(S.account?.user?.name||'—')+'</b></div><div><span>Rating</span><b>'+num(S.account?.user?.rating_avg)+' · '+num(S.account?.user?.rating_count,0)+' valoraciones</b></div><div><span>Telegram</span><b>'+(S.account?.user?.telegram_verified?'Verificado':'—')+'</b></div><div><span>Teléfono</span><b>'+(S.account?.user?.phone_verified?'Verificado':'—')+'</b></div><div><span>Golden Check</span><b>'+(S.account?.user?.golden_check?'Activo':'—')+'</b></div></div>')+card('Seguridad','Diseño de integración','<div class="security-list"><div>🔐 <b>Secret</b><span>Nunca llega al navegador.</span></div><div>🧱 <b>Proxy</b><span>Operaciones pasan por servidor.</span></div><div>🛡️ <b>Control</b><span>Kill switch y límites.</span></div></div>')+'</div>',
 '/finance':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">FINANCIAL INTELLIGENCE</div><h1>Finanzas</h1><p>Ingresos, gastos, inventario QUSD y resultado realizado a partir de operaciones P2P completadas.</p></div><button class="button primary" onclick="refreshFinance()">↻ Actualizar</button></div><div class="metrics-grid">'+metric('Ingresos',S.finance?num(S.finance.fiatIncome,2):'—','Fiat recibido · ventas','↗')+metric('Gastos',S.finance?num(S.finance.fiatExpense,2):'—','Fiat entregado · compras','↘')+metric('Resultado',S.finance?.realizedProfitKnown?num(S.finance.realizedProfit,2):'—','Beneficio realizado','¤')+metric('Inventario',S.finance?num(S.finance.inventoryQusd,2):'—','QUSD disponible por lotes','◈')+'</div>'+card('Resumen financiero','Contabilidad derivada de operaciones completadas','<div class="finance-summary"><div><span>Operaciones completadas</span><b>'+num(S.finance?.completedCount,0)+'</b></div><div><span>Coste desconocido</span><b>'+num(S.finance?.unknownCostQusd,2)+' QUSD</b></div><div><span>Estado del resultado</span><b>'+(S.finance?.realizedProfitKnown?'Coste conocido':'Coste parcial')+'</b></div></div>'+(S.finance?.realizedProfitKnown?'':'<div class="finance-note">⚠️ El resultado no se presenta como definitivo porque existen ventas cuyo coste de adquisición todavía no está en el ledger.</div>')+'</section>'),
'/settings':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">SYSTEM</div><h1>Configuración</h1><p>Preferencias de la experiencia.</p></div></div><div class="settings-list"><div class="setting"><div><b>Mercado</b><p>Actualización manual.</p></div><span class="chip">Manual</span></div><div class="setting"><div><b>Operación</b><p>Seguimiento periódico.</p></div><span class="chip">10 s</span></div><div class="setting"><div><b>Ejecución</b><p>Auto-Apply separado de pagos.</p></div><span class="chip">Seguro</span></div><div class="setting"><div><b>Interfaz</b><p>Responsive móvil/escritorio.</p></div><span class="chip">Activa</span></div></div></div>'};
function populateCoinFilter(){const s=$('fc');if(!s)return;const current=s.value;const coins=[...new Set(S.offers.map(o=>String(o.coin||'').trim()).filter(Boolean))].sort();s.innerHTML='<option value="">Todas las monedas</option>'+coins.map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join('');if(coins.includes(current))s.value=current}
function updateFilterCount(){const ids=['ft','fc','fo','fd','fmin','fmax','frmin','frmax'];const active=ids.filter(id=>{const v=$(id)?.value??'';return id==='fo'?v!=='updated_at':id==='fd'?v!=='desc':String(v).trim()!==''}).length;const bestOption=$('fo')?.querySelector('option[value="best_rate"]');const canBest=Boolean($('ft')?.value&&$('fc')?.value);if(bestOption)bestOption.disabled=!canBest;if(!canBest&&$('fo')?.value==='best_rate')$('fo').value='updated_at';const e=$('filterCount');if(e)e.textContent=active+' filtro'+(active===1?'':'s')+' activo'+(active===1?'':'s')}
function bindFilters(){const f=$('filters');if(!f)return;populateCoinFilter();updateFilterCount();f.onsubmit=e=>{e.preventDefault();S.page=1;refreshMarket()};f.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',updateFilterCount));f.querySelectorAll('select').forEach(el=>el.addEventListener('change',updateFilterCount))}
function resetFilters(){['ft','fc','fmin','fmax','frmin','frmax'].forEach(id=>{const e=$(id);if(e)e.value=''});if($('fo'))$('fo').value='updated_at';if($('fd'))$('fd').value='desc';updateFilterCount();S.page=1;refreshMarket()}
function params(){const orderBy=$('fo')?.value||'updated_at',type=$('ft')?.value||'',coin=$('fc')?.value||'';const safeOrder=orderBy==='best_rate'&&(!type||!coin)?'updated_at':orderBy;const p=new URLSearchParams({page:S.page,take:'100',orderBy:safeOrder,orderType:$('fd')?.value||'desc'});[['ft','type'],['fc','coin'],['fmin','min'],['fmax','max'],['frmin','ratio_min'],['frmax','ratio_max']].forEach(x=>{const v=$(x[0])?.value?.trim();if(v)p.set(x[1],v)});return p}
async function refreshMarket(){try{const p=await api('/api/p2p?'+params());S.offers=p.data||[];S.total=Number(p.total??S.offers.length);S.lastPage=Math.max(1,Math.ceil(S.total/Number(p.per_page||100)));nav();toast('Mercado sincronizado','success')}catch(e){toast(e.message,'error')}}
function userBadges(u){const items=[u.kyc?['🪪','KYC verificado']:null,u.vip?['💎','VIP']:null,u.golden_check?['👑','Golden Check']:null,u.phone_verified?['📱','Teléfono verificado']:null,u.telegram_verified?['💬','Telegram verificado']:null].filter(Boolean);return items.length?items.map(x=>'<span class="user-badge" title="'+esc(x[1])+'" aria-label="'+esc(x[1])+'">'+x[0]+'</span>').join(''):'<span class="user-badge muted" title="Sin verificaciones informadas">—</span>'}
function drawOffers(){const b=$('offers');if(!b)return;b.innerHTML=S.offers.length?S.offers.map(o=>{const u=o.User||{},v=rate(o),id=String(o.uuid??o.id??'');return '<tr><td><span class="type '+esc(o.type)+'">'+esc(o.type)+'</span></td><td>'+esc(o.coin)+'</td><td class="strong">'+num(v,2)+'</td><td>'+num(o.amount,2)+'</td><td>'+num(o.receive,2)+'</td><td>'+num(o.available_amount,2)+'</td><td><div class="user-cell"><b><span class="user-icon">👤</span>'+esc(u.username||u.name||'—')+'</b><small>'+esc(u.name&&u.username?u.name:'')+'</small><div class="user-badges">'+userBadges(u)+'</div></div></td><td><span class="rating-value">⭐ '+num(u.rating_avg,2)+'</span><small>'+num(u.rating_count,0)+' valoraciones</small></td><td><button class="button primary compact" onclick="applyOffer(\''+esc(id)+'\')">Aplicar</button></td></tr>'}).join(''):'<tr><td colspan="9" class="empty-cell">No hay ofertas.</td></tr>'}
async function applyOffer(id){if(!confirm('Aplicar a esta oferta ahora?'))return;try{await api('/api/p2p/'+encodeURIComponent(id)+'/apply',{method:'POST'});S.active=id;localStorage.setItem('qvapay.activeOperationId',id);await loadOperation();toast('Aplicación aceptada por QvaPay','success')}catch(e){toast(e.message,'error')}}
async function loadOperation(){if(!S.active)return;try{const p=await api('/api/p2p/'+encodeURIComponent(S.active));S.operation=p?.qvapay?.p2p??p?.qvapay?.data??p?.qvapay??p?.data??p;if((location.hash.slice(1)||'/')==='/operations')nav()}catch(e){}}
function opCard(){const o=S.operation||{};return '<section class="card operation-live"><div class="operation-top"><div><span class="eyebrow">LIVE OPERATION</span><h2>'+esc(String(o.type||'P2P').toUpperCase())+' · '+esc(o.coin||'—')+'</h2></div><span class="status-chip">● '+esc(String(o.status||o.state||'PROCESSING').toUpperCase())+'</span></div><div class="operation-grid"><div><span>UUID</span><b>'+esc(S.active)+'</b></div><div><span>Monto</span><b>'+num(o.amount)+'</b></div><div><span>Recibe</span><b>'+num(o.receive)+'</b></div><div><span>Contraparte</span><b>'+esc(o.User?.username||o.user?.username||o.Peer?.username||'—')+'</b></div><div><span>Actualizado</span><b>'+time(o.updated_at||o.updatedAt)+'</b></div></div><div class="operation-actions"><button class="button secondary" onclick="loadOperation()">↻ Actualizar</button><a class="button ghost" href="#/market">Mercado</a></div></section>'}
function drawHome(){const e=$('miniOffers');if(e)e.innerHTML=S.offers.slice(0,6).map(o=>'<div class="mini-row"><span class="type '+esc(o.type)+'">'+esc(o.type)+'</span><b>'+esc(o.coin)+'</b><strong>'+num(rate(o),2)+'</strong><span>'+num(o.amount,2)+' QUSD</span></div>').join('')||'<div class="empty-inline">Sin datos.</div>'}
function drawBars(){const e=$('bars');if(!e)return;const a=(S.intelligence?.opportunities||[]).map(x=>x.rate).filter(Number.isFinite).slice(0,12),m=Math.max(...a);e.innerHTML=a.length?a.map((v,i)=>'<div class="bar-row"><span>#'+(i+1)+'</span><div><i style="width:'+Math.max(5,v/m*100)+'%"></i></div><b>'+num(v,2)+'</b></div>').join(''):'<div class="empty-inline">Sin señales en el snapshot actual.</div>'};
function drawCoinRadar(){const e=$('coinRadar');if(!e)return;const groups=S.intelligence?.byCoin||[];e.innerHTML=groups.length?groups.map(g=>{return '<section class="coin-radar"><div class="coin-radar-head"><div><span class="eyebrow">RADAR · '+esc(g.coin)+'</span><h3>'+esc(g.coin)+'</h3></div><span class="chip">'+num(g.opportunities.length,0)+' oportunidades</span></div><div class="coin-radar-stats"><span>'+num(g.sampleSize,0)+' muestras</span><span>Mediana '+num(g.medianRate,2)+'</span><span>Mejor '+num(g.bestRate,2)+'</span></div><div class="opportunity-list">'+(g.opportunities.length?g.opportunities.slice(0,6).map((o,i)=>'<div class="opportunity-row"><div class="opportunity-rank">#'+(i+1)+'</div><div class="opportunity-main"><b>'+esc(o.type.toUpperCase())+' · '+num(o.rate,2)+'</b><small>'+num(o.amount,2)+' QUSD · '+num(o.receive,2)+' '+esc(g.coin)+'</small></div><div class="opportunity-score"><span style="width:'+Math.max(8,Math.min(100,Number(o.score)||0))+'%"></span><b>'+num(o.score,0)+'</b></div></div>').join(''):'<div class="empty-inline">Sin oportunidades calculables.</div>')+'</div></section>'}).join(''):'<div class="empty-inline">No hay datos suficientes para construir radares por moneda.</div>'}
function drawCoinAnalysis(){const e=$('coinAnalysis');if(!e)return;const rows=S.intelligence?.byCoin||[];e.innerHTML=rows.length?rows.map(g=>'<section class="coin-analysis"><div class="coin-analysis-head"><div><span class="eyebrow">MONEDA</span><h3>'+esc(g.coin)+'</h3></div><span class="chip">'+num(g.sampleSize,0)+' ofertas</span></div><div class="coin-metrics"><div><span>Mejor tasa</span><b>'+num(g.bestRate,2)+'</b></div><div><span>Mediana</span><b>'+num(g.medianRate,2)+'</b></div><div><span>Tasa mínima</span><b>'+num(g.minRate,2)+'</b></div><div><span>Spread</span><b>'+num(g.spread,2)+'</b></div><div><span>SELL</span><b>'+num(g.sellCount,0)+'</b></div><div><span>BUY</span><b>'+num(g.buyCount,0)+'</b></div><div><span>Abiertas</span><b>'+num(g.openCount,0)+'</b></div></div></section>').join(''):'<div class="empty-inline">No hay datos suficientes para separar el análisis por moneda.</div>'}
function historySummary(){if(!S.history.length)return '<div class="empty-inline">Aún no existe histórico suficiente. El collector comenzará a acumular observaciones.</div>';const groups=new Map();S.history.forEach(p=>{const key=String(p.coin||'SIN_MONEDA')+'|'+String(p.type||'').toUpperCase();const a=groups.get(key)||[];a.push(p);groups.set(key,a)});const rows=[...groups.values()].map(points=>{const last=points[points.length-1],prev=points.length>1?points[points.length-2]:null;const delta=last?.medianRate!=null&&prev?.medianRate!=null?last.medianRate-prev.medianRate:null;return '<div><span>'+esc(String(last?.coin||'—'))+' · '+esc(String(last?.type||'').toUpperCase())+'</span><b>'+num(last?.medianRate,2)+'</b><small>'+(delta==null?'Sin variación previa':(delta>=0?'+':'')+num(delta,2)+' vs. punto anterior')+' · '+num(points.length,0)+' puntos</small></div>'}).slice(0,8);return '<div class="history-summary coin-history">'+rows.join('')+'</div>'}
function trendSummary(){if(!S.trends.length)return '<div class="empty-inline">Esperando observaciones suficientes para calcular tendencias.</div>';return S.trends.slice(0,6).map(t=>'<div class="trend-row"><div><b>'+esc(t.type.toUpperCase())+' · '+esc(t.coin)+'</b><small>'+num(t.points,0)+' puntos · '+time(t.lastTimestamp)+'</small></div><strong class="trend-'+t.direction+'">'+(t.changePercent==null?'—':(t.changePercent>=0?'+':'')+num(t.changePercent,2)+'%')+'</strong></div>').join('')}
function baselineSummary(){if(!S.baselines.length)return '';return S.baselines.slice(0,6).map(b=>'<div class="trend-row"><div><b>'+esc(b.type.toUpperCase())+' · '+esc(b.coin)+'</b><small>Base '+num(b.baselineRate,2)+' · Actual '+num(b.currentRate,2)+'</small></div><strong class="trend-'+b.status+'">'+(b.deviationPercent==null?'—':(b.deviationPercent>=0?'+':'')+num(b.deviationPercent,2)+'%')+'</strong></div>').join('')}
function changePage(d){if(S.page+d<1||S.page+d>S.lastPage)return;S.page+=d;refreshMarket()}
function operationRole(o){
  const current=o?.currentUserId;
  const username=String(S.account?.user?.username||'').replace(/^@/,'').toLowerCase();
  const same=(a,b)=>a!=null&&b!=null&&String(a)===String(b);
  const sameUsername=(a)=>username&&String(a||'').replace(/^@/,'').toLowerCase()===username;
  if(same(o?.User?.uuid,current)||same(o?.User?.id,current)||sameUsername(o?.User?.username))return'owner';
  if(same(o?.Peer?.uuid,current)||same(o?.Peer?.id,current)||sameUsername(o?.Peer?.username))return'peer';
  return'unknown';
}
function operationActions(o,role=operationRole(o)){
  const type=String(o?.type||'').toLowerCase(),status=String(o?.status||'').toLowerCase(),a=['chat'];
  if(status==='processing'&&((type==='buy'&&role==='owner')||(type==='sell'&&role==='peer')))a.unshift('paid');
  if(status==='paid'&&((type==='sell'&&role==='owner')||(type==='buy'&&role==='peer')))a.unshift('received');
  if(['processing','paid'].includes(status))a.push('cancel');
  if(status==='revision'&&((type==='buy'&&role==='owner')||(type==='sell'&&role==='peer')))a.push('cancel');
  if(status==='completed')a.unshift('rate');
  return [...new Set(a)];
}
function operationActionCount(){
  return S.operations.filter(o=>operationActions(o).some(a=>a==='paid'||a==='received')).length;
}
function operationStatusLabel(v){return({revision:'REVISIÓN',processing:'PROCESANDO',paid:'PAGADA',open:'ABIERTA',completed:'COMPLETADA',cancelled:'CANCELADA'}[String(v||'').toLowerCase()]||String(v||'—').toUpperCase())}
function operationCounterparty(o,role=operationRole(o)){const p=role==='owner'?o?.Peer:role==='peer'?o?.User:(o?.Peer||o?.User);return p?.username||p?.name||'—'}
function operationRate(o){return Number(o?.amount)>0?Number(o?.receive)/Number(o?.amount):null}
function operationActionButton(action){
  if(action==='paid')return'<button class="button primary compact" onclick="markOperationPaid()">✓ Marcar pagada</button>';
  if(action==='received')return'<button class="button primary compact" onclick="markOperationReceived()">✓ Confirmar recepción</button>';
  if(action==='cancel')return'<button class="button danger compact" onclick="cancelOperation()">Cancelar</button>';
  if(action==='rate')return'<button class="button secondary compact" onclick="rateOperation()">⭐ Calificar</button>';
  return'';
}
function drawOperations(){
  const list=$('operationsList');if(!list)return;
  const status=$('ofStatus')?.value||'',type=$('ofType')?.value||'',coin=($('ofCoin')?.value||'').trim().toUpperCase();
  const rows=S.operations.filter(o=>(!status||String(o.status||'').toLowerCase()===status)&&(!type||String(o.type||'').toLowerCase()===type)&&(!coin||String(o.coin||'').toUpperCase().includes(coin)));
  list.innerHTML=rows.length?rows.map(o=>{const id=String(o.uuid||''),active=id===S.active,role=operationRole(o),actions=operationActions(o,role);return'<button class="operation-row '+(active?'selected':'')+'" onclick="selectOperation(\''+esc(id)+'\')"><div><span class="operation-status">'+operationStatusLabel(o.status)+'</span><b>'+esc(String(o.type||'P2P').toUpperCase())+' · '+esc(o.coin||'—')+'</b><small>'+esc(operationCounterparty(o,role))+' · '+num(o.amount,2)+' QUSD</small></div><div class="operation-row-rate"><b>'+num(operationRate(o),2)+'</b><small>'+num(o.receive,2)+'</small></div><span class="operation-row-action">'+((actions.includes('paid')||actions.includes('received'))?'⚡':'›')+'</span></button>'}).join(''):'<div class="empty-inline">No hay operaciones que coincidan con los filtros.</div>';
  if($('operationDetail'))drawOperationDetail();
  $('ofStatus')?.addEventListener('change',drawOperations);$('ofType')?.addEventListener('change',drawOperations);$('ofCoin')?.addEventListener('input',drawOperations);
}
function drawOperationDetail(){
  const e=$('operationDetail');if(!e||!S.operation)return;
  const o=S.operation,role=operationRole(o),actions=operationActions(o,role),details=o.details&&typeof o.details==='object'?JSON.stringify(o.details,null,2):'—';
  e.innerHTML='<div class="operation-detail-head"><div><span class="eyebrow">OPERACIÓN '+esc(String(o.uuid||S.active))+'</span><h2>'+esc(String(o.type||'P2P').toUpperCase())+' · '+esc(o.coin||'—')+'</h2><p>'+operationStatusLabel(o.status)+' · Rol: '+(role==='owner'?'CREADOR':role==='peer'?'CONTRAPARTE':'NO DETERMINADO')+' · '+esc(operationCounterparty(o,role))+'</p></div><span class="status-chip">'+operationStatusLabel(o.status)+'</span></div><div class="operation-grid"><div><span>QUSD</span><b>'+num(o.amount,2)+'</b></div><div><span>Recibe</span><b>'+num(o.receive,2)+'</b></div><div><span>Tasa</span><b>'+num(operationRate(o),2)+'</b></div><div><span>TX ID</span><b>'+esc(o.tx_id||'—')+'</b></div><div><span>Actualizado</span><b>'+time(o.updated_at||o.updatedAt)+'</b></div></div><div class="operation-details-block"><span>Datos de pago</span><pre>'+esc(details)+'</pre></div><div class="operation-actions">'+actions.filter(a=>a!=='chat').map(operationActionButton).join('')+'</div><div class="operation-chat"><div class="chat-head"><b>💬 Chat</b><button class="button ghost compact" onclick="loadChat()">↻</button></div><div id="chatMessages" class="chat-messages"></div><form id="chatForm" class="chat-form"><input id="chatMessage" maxlength="599" placeholder="Escribe un mensaje a la contraparte…"><button class="button secondary compact">Enviar</button></form></div></div>';
  drawChat();
  $('chatForm')?.addEventListener('submit',sendChat);
}
function drawChat(){
  const e=$('chatMessages');if(!e)return;
  e.innerHTML=S.chat.length?S.chat.map(m=>'<div class="chat-message"><p>'+esc(m.message||'')+'</p><small>'+time(m.created_at||m.createdAt)+'</small></div>').join(''):'<div class="empty-inline">Sin mensajes todavía.</div>';
  e.scrollTop=e.scrollHeight;
}
async function selectOperation(id){S.active=id;localStorage.setItem('qvapay.activeOperationId',id);await loadOperation(id);drawOperations();toast('Operación seleccionada','success')}
async function loadOperations(){try{const p=await api('/api/operations');const q=p.operations||{};S.operations=Array.isArray(q)?q:(q.data||[]);if(S.active&&!S.operations.some(o=>String(o.uuid)===String(S.active))){S.active=null;S.operation=null;S.chat=[];localStorage.removeItem('qvapay.activeOperationId')}if(!S.active){const pending=S.operations.find(o=>['processing','paid','revision'].includes(String(o.status||'').toLowerCase()));if(pending){S.active=String(pending.uuid);localStorage.setItem('qvapay.activeOperationId',S.active)}}}catch(e){S.operations=[]}}
async function loadOperation(id=S.active){if(!id)return;try{const p=await api('/api/p2p/'+encodeURIComponent(id));S.operation=p?.qvapay?.p2p??p?.qvapay?.data??p?.qvapay??p?.data??p;S.active=id;S.operationRole=operationRole(S.operation);await loadChat();if((location.hash.slice(1)||'/')==='/operations'){drawOperations();drawOperationDetail()}}catch(e){toast(e.message,'error')}}
async function loadChat(){if(!S.active)return;try{const p=await api('/api/operations/'+encodeURIComponent(S.active)+'/chat');const q=p?.qvapay;S.chat=Array.isArray(q?.chat)?q.chat:Array.isArray(q?.data)?q.data:Array.isArray(q)?q:[]}catch(e){S.chat=[]}}
async function markOperationPaid(){if(!S.active)return;const tx=prompt('Introduce el identificador/referencia del pago (tx_id):','');if(tx==null||!tx.trim())return;try{await api('/api/operations/'+encodeURIComponent(S.active)+'/paid',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tx_id:tx.trim()})});toast('Pago registrado en QvaPay','success');await refreshOperations()}catch(e){toast(e.message,'error')}}
async function markOperationReceived(){if(!S.active||!confirm('¿Confirmas que recibiste el pago fiat? Esta acción completa la operación en QvaPay.'))return;try{await api('/api/operations/'+encodeURIComponent(S.active)+'/received',{method:'POST'});toast('Recepción confirmada y operación completada','success');await refreshOperations()}catch(e){toast(e.message,'error')}}
async function cancelOperation(){if(!S.active||!confirm('¿Cancelar esta operación? QvaPay determinará el resultado según tu rol y el estado.'))return;try{await api('/api/operations/'+encodeURIComponent(S.active)+'/cancel',{method:'POST'});toast('Solicitud de cancelación enviada','success');await refreshOperations()}catch(e){toast(e.message,'error')}}
async function rateOperation(){if(!S.active)return;const rating=Number(prompt('Calificación de la contraparte (1 a 5):','5'));if(!Number.isFinite(rating)||rating<1||rating>5)return;const comment=prompt('Comentario opcional (máximo 120 caracteres):','')??'';try{await api('/api/operations/'+encodeURIComponent(S.active)+'/rate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating,comment})});toast('Calificación enviada','success');await loadOperation(S.active)}catch(e){toast(e.message,'error')}}
async function sendChat(e){e.preventDefault();const input=$('chatMessage'),message=input?.value.trim();if(!message||!S.active)return;try{await api('/api/operations/'+encodeURIComponent(S.active)+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});input.value='';await loadChat();drawChat();toast('Mensaje enviado','success')}catch(err){toast(err.message,'error')}}
function drawAccount(){if(!S.account)return} function drawFinance(){if(!S.finance)return}
async function refreshOperations(){await loadOperations();if(S.active)await loadOperation(S.active);nav();toast('Operaciones sincronizadas','success')}
async function refreshAccount(){try{const p=await api('/api/account');S.account=p.account;nav();toast('Cuenta sincronizada','success')}catch(e){toast(e.message,'error')}}
async function refreshFinance(){try{const p=await api('/api/finance');S.finance=p.finance;nav();toast('Finanzas sincronizadas','success')}catch(e){toast(e.message,'error')}}
async function loadAccount(){try{const p=await api('/api/account');S.account=p.account}catch(e){S.account=null}}
async function loadFinance(){try{const p=await api('/api/finance');S.finance=p.finance}catch(e){S.finance=null}}
async function loadAuto(){try{const a=await api('/api/auto-apply/config'),b=await api('/api/auto-apply/status');S.config=a.config;S.auto=b.status}catch(e){}}
function bindAuto(){const f=$('af');if(!f)return;$('at').value=S.config?.type||'sell';f.onsubmit=async e=>{e.preventDefault();const val=id=>$(id).value.trim()===''?null:Number($(id).value),en=$('ae').checked;if(en&&!S.config?.enabled&&!confirm('Activar Auto-Apply?'))return;try{await api('/api/auto-apply/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:en,type:$('at').value,coin:$('ac').value.trim().toUpperCase(),rateMin:val('arm'),rateMax:val('arx'),amountMin:val('aom'),amountMax:val('aox'),dailyMaxQusd:val('adl'),maxConcurrent:Number($('acon').value)})});await loadAuto();nav();toast('Reglas guardadas','success')}catch(e){toast(e.message,'error')}}}
async function loadMarket(){try{const p=await api('/api/p2p?page=1&take=100&orderBy=updated_at&orderType=desc');S.offers=p.data||[];S.total=Number(p.total??S.offers.length);S.lastPage=Math.max(1,Math.ceil(S.total/Number(p.per_page||100)))}catch(e){}}
async function loadIntelligence(){try{const p=await api('/api/intelligence?page=1&take=100&orderBy=updated_at&orderType=desc');S.intelligence=p.intelligence;S.intelligenceCoverage=p.coverage?{sampled:Number(p.intelligence?.sampleSize||0),total:Number(p.coverage.total||0),truncated:Boolean(p.coverage.truncated)}:null}catch(e){S.intelligence=null;S.intelligenceCoverage=null}}
async function loadHistory(){try{const p=await api('/api/history?limit=200');S.history=p.history||[]}catch(e){S.history=[]}}
async function loadTrends(){try{const p=await api('/api/trends');S.trends=p.trends||[]}catch(e){S.trends=[]}}
async function loadBaselines(){try{const p=await api('/api/baselines?lookback=24');S.baselines=p.baselines||[]}catch(e){S.baselines=[]}}
async function refreshAll(){await Promise.all([loadMarket(),loadIntelligence(),loadHistory(),loadTrends(),loadBaselines(),loadAuto(),loadAccount(),loadFinance(),loadOperations()]);if(S.active)await loadOperation(S.active);nav();toast('Scanner sincronizado','success')}
window.refreshAll=refreshAll;window.refreshMarket=refreshMarket;window.changePage=changePage;window.applyOffer=applyOffer;window.loadOperation=loadOperation;window.loadOperations=loadOperations;window.refreshOperations=refreshOperations;window.selectOperation=selectOperation;window.markOperationPaid=markOperationPaid;window.markOperationReceived=markOperationReceived;window.cancelOperation=cancelOperation;window.rateOperation=rateOperation;window.loadChat=loadChat;window.resetFilters=resetFilters;
const commands=Object.entries(meta).map(([href,v])=>({href,label:v[1],group:v[0]}));
function renderCommands(q=''){const box=$('commandResults');if(!box)return;const list=commands.filter(x=>(x.label+' '+x.group).toLowerCase().includes(q.toLowerCase()));box.innerHTML=list.map((x,i)=>'<a class="command-item'+(i===0?' selected':'')+'" href="#'+x.href+'"><b>'+x.label+'</b><small>'+x.group+'</small></a>').join('')||'<div class="command-item">Sin resultados</div>'}
function openCommands(){const p=$('commandPalette');if(!p)return;p.classList.add('open');p.setAttribute('aria-hidden','false');$('commandInput').value='';renderCommands();setTimeout(()=>$('commandInput').focus(),20)}
function closeCommands(){const p=$('commandPalette');if(p){p.classList.remove('open');p.setAttribute('aria-hidden','true')}}
function setupCommands(){document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommands()}if(e.key==='Escape')closeCommands()});$('commandBackdrop')?.addEventListener('click',closeCommands);$('commandInput')?.addEventListener('input',e=>renderCommands(e.target.value));document.querySelector('.mobile-nav')?.addEventListener('click',closeCommands)}
window.refreshAccount=refreshAccount;window.refreshFinance=refreshFinance;window.openCommands=openCommands;
async function init(){document.getElementById('menuButton').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('mobileOverlay').onclick=()=>document.getElementById('sidebar').classList.remove('open');document.getElementById('refreshButton').onclick=refreshAll;document.getElementById('commandButton')?.addEventListener('click',openCommands);setupCommands();addEventListener('hashchange',nav);await Promise.all([loadMarket(),loadIntelligence(),loadHistory(),loadAuto(),loadAccount(),loadFinance(),loadOperations()]);if(S.active)await loadOperation(S.active);nav();setInterval(loadAuto,5000);setInterval(()=>S.active&&loadOperation(S.active),10000)}init();