const S={offers:[],total:0,page:1,lastPage:1,active:localStorage.getItem('qvapay.activeOperationId'),operation:null,config:null,auto:null};
const $=id=>document.getElementById(id), esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const num=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString('es-ES',{maximumFractionDigits:d}):'—'; const rate=o=>Number(o?.amount)>0?Number(o.receive)/Number(o.amount):null;
const meta={'/':['OVERVIEW','Inicio'],'/market':['MARKET','Mercado'],'/auto-apply':['AUTOMATION','Auto-Apply'],'/operations':['OPERATIONS','Operaciones'],'/analytics':['INTELLIGENCE','Analytics'],'/alerts':['MONITORING','Alertas'],'/account':['ACCOUNT','Cuenta'],'/settings':['SYSTEM','Configuración']};
async function api(u,o={}){const r=await fetch(u,{cache:'no-store',...o}),p=await r.json();if(!r.ok)throw Error(p?.detail?.message||p?.detail||p?.error||'Error');return p}
function toast(m,c='info'){const x=document.createElement('div');x.className='toast '+c;x.textContent=m;document.getElementById('toasts').append(x);setTimeout(()=>x.remove(),3500)}
function card(t,s,b){return '<section class="card"><div class="card-head"><div><h2>'+t+'</h2><p>'+s+'</p></div></div>'+b+'</section>'} function metric(a,b,c,i){return '<article class="metric"><div class="metric-icon">'+i+'</div><span>'+a+'</span><strong>'+b+'</strong><small>'+c+'</small></article>'}
function time(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleTimeString('es-ES')}
function best(){const a=S.offers.map(rate).filter(Number.isFinite);return a.length?num(Math.max(...a),4):'—'} function low(){const a=S.offers.map(rate).filter(Number.isFinite);return a.length?num(Math.min(...a),4):'—'}
function nav(){let p=location.hash.slice(1)||'/';if(!meta[p])p='/';document.getElementById('pageKicker').textContent=meta[p][0];document.getElementById('pageTitle').textContent=meta[p][1];document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+p));document.getElementById('app').innerHTML=pages[p]();if(p==='/market'){bindFilters();drawOffers()}if(p==='/auto-apply')bindAuto();if(p==='/analytics')drawBars();if(p==='/')drawHome();if(p==='/operations'&&S.active)loadOperation()}
const pages={
'/':()=>'<div class="page"><div class="hero"><div><div class="eyebrow">CONTROL CENTER</div><h1>Buenos días, <em>Scanner.</em></h1><p>Un centro de mando para observar, automatizar y entender tu mercado P2P.</p></div><button class="button primary" onclick="refreshAll()">↻ Sincronizar</button></div><div class="metrics-grid">'+metric('Ofertas',num(S.total,0),'Mercado QvaPay','◈')+metric('Tasa destacada',best(),'Snapshot','↗')+metric('Auto-Apply',S.auto?.running?'ACTIVO':'PAUSADO','Motor','✦')+metric('Operación',S.operation?'ACTIVA':'NINGUNA','Tracker','↻')+'</div><div class="grid-2">'+card('Radar del mercado','Últimas ofertas','<div id="miniOffers"></div>')+card('Automatización','Estado','<div class="automation-card"><div class="pulse '+(S.auto?.running?'on':'')+'"></div><div><b>'+(S.auto?.running?'Motor activo':'Motor pausado')+'</b><p>'+esc(S.auto?.lastMessage||'Configura tus reglas.')+'</p></div><a href="#/auto-apply">Configurar →</a></div>')+'</div>'+card('Acceso rápido','Flujo operativo','<div class="quick-grid"><a href="#/market">◈<b>Mercado</b><span>Explorar ofertas</span></a><a href="#/operations">↻<b>Operaciones</b><span>Seguimiento</span></a><a href="#/analytics">⌁<b>Analytics</b><span>Inteligencia</span></a><a href="#/alerts">◉<b>Alertas</b><span>Monitoreo</span></a></div>')+'</div>',
'/market':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">LIVE MARKET</div><h1>Mercado P2P</h1><p>Filtra, compara y aplica a ofertas desde una interfaz profesional.</p></div><button class="button primary" onclick="refreshMarket()">↻ Actualizar</button></div>'+card('Filtros','Control preciso','<form id="filters" class="filter-grid"><label>Tipo<select id="ft"><option value="">Todos</option><option value="sell">Sell</option><option value="buy">Buy</option></select></label><label>Moneda<input id="fc" placeholder="BANK_CUP"></label><label>Orden<select id="fo"><option value="updated_at">Actualización</option><option value="best_rate">Mejor tasa</option><option value="amount">Monto</option><option value="receive">Recepción</option></select></label><label>Dirección<select id="fd"><option value="desc">Descendente</option><option value="asc">Ascendente</option></select></label><label>Mínimo<input id="fmin" type="number" step="any"></label><label>Máximo<input id="fmax" type="number" step="any"></label><button class="button secondary">Aplicar</button></form>')+card('Ofertas',num(S.total,0)+' resultados · página '+S.page+' / '+S.lastPage,'<div class="table-wrap"><table><thead><tr><th>Tipo</th><th>Moneda</th><th>Tasa</th><th>QUSD</th><th>Recibe</th><th>Disponible</th><th>Usuario</th><th>Rating</th><th></th></tr></thead><tbody id="offers"></tbody></table></div><div class="pager"><button class="button secondary" onclick="changePage(-1)">←</button><span>'+S.page+'</span><button class="button secondary" onclick="changePage(1)">→</button></div>')+'</div>',
'/auto-apply':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">AUTOMATION ENGINE</div><h1>Auto-Apply</h1><p>Reglas configurables para aplicar automáticamente a ofertas elegibles.</p></div><div class="engine-badge '+(S.auto?.running?'live':'')+'"><i></i>'+(S.auto?.running?'ACTIVO':'PAUSADO')+'</div></div><div class="grid-2"><section class="card accent-card"><div class="card-head"><div><h2>Reglas</h2><p>Controla cada condición.</p></div></div><form id="af" class="form-grid"><label>Estado<input id="ae" type="checkbox" '+(S.config?.enabled?'checked':'')+'></label><label>Tipo<select id="at"><option value="sell">Sell</option><option value="buy">Buy</option></select></label><label>Moneda<input id="ac" value="'+esc(S.config?.coin||'')+'"></label><label>Tasa mínima<input id="arm" type="number" step="any" value="'+(S.config?.rateMin??'')+'"></label><label>Tasa máxima<input id="arx" type="number" step="any" value="'+(S.config?.rateMax??'')+'"></label><label>Monto mínimo<input id="aom" type="number" step="any" value="'+(S.config?.amountMin??'')+'"></label><label>Monto máximo<input id="aox" type="number" step="any" value="'+(S.config?.amountMax??'')+'"></label><label>Límite diario<input id="adl" type="number" step="any" value="'+(S.config?.dailyMaxQusd??'')+'"></label><label>Máx. simultáneas<input id="acon" type="number" min="1" value="'+(S.config?.maxConcurrent??1)+'"></label><button class="button primary wide">Guardar reglas</button></form></section>'+card('Telemetría','Estado del runtime','<div class="telemetry"><div><span>Aplicado hoy</span><b>'+num(S.auto?.dailyAppliedQusd)+' QUSD</b></div><div><span>Escaneo</span><b>'+time(S.auto?.lastScanAt)+'</b></div><div><span>Acción</span><b>'+time(S.auto?.lastActionAt)+'</b></div><div><span>Mensaje</span><b>'+esc(S.auto?.lastMessage||'—')+'</b></div></div><div class="guard">🛡️ Kill switch · límites locales · sin pagos automáticos</div>')+'</div></div>',
'/operations':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">EXECUTION</div><h1>Operaciones</h1><p>Seguimiento de la operación asignada.</p></div></div>'+(S.operation?opCard():'<div class="empty-state"><div>↻</div><h2>No hay operación activa</h2><p>Aplica a una oferta para iniciar seguimiento.</p><a href="#/market" class="button primary">Ir al mercado</a></div>')+'</div>',
'/analytics':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">MARKET INTELLIGENCE</div><h1>Analytics</h1><p>Lecturas del snapshot actualmente cargado.</p></div></div><div class="metrics-grid">'+metric('Muestras',num(S.offers.length,0),'Snapshot','◌')+metric('Máxima',best(),'Tasa','↗')+metric('Mínima',low(),'Tasa','↘')+metric('Monedas',new Set(S.offers.map(x=>x.coin)).size,'Snapshot','◇')+'</div>'+card('Distribución de tasas','Ofertas cargadas','<div id="bars" class="bars"></div>')+'</div>',
'/alerts':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">MONITORING</div><h1>Alertas</h1><p>Eventos que requieren atención.</p></div></div><div class="alert-list"><div class="alert-item info"><span>◉</span><div><b>Mercado conectado</b><p>Consulta protegida mediante backend.</p></div><time>Ahora</time></div><div class="alert-item '+(S.auto?.running?'success':'neutral')+'"><span>✦</span><div><b>Auto-Apply '+(S.auto?.running?'activo':'pausado')+'</b><p>'+esc(S.auto?.lastMessage||'Sin eventos.')+'</p></div><time>'+time(S.auto?.lastActionAt)+'</time></div></div></div>',
'/account':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">ACCOUNT</div><h1>Cuenta</h1><p>Estado de integración y seguridad.</p></div></div><div class="account-card"><div class="account-avatar">Q</div><div><span class="eyebrow">INTEGRACIÓN</span><h2>QvaPay App</h2><p>Las credenciales permanecen en el backend.</p></div><span class="chip success">Conectada</span></div>'+card('Seguridad','Diseño de integración','<div class="security-list"><div>🔐 <b>Secret</b><span>Nunca llega al navegador.</span></div><div>🧱 <b>Proxy</b><span>Operaciones pasan por servidor.</span></div><div>🛡️ <b>Control</b><span>Kill switch y límites.</span></div></div>')+'</div>',
'/settings':()=>'<div class="page"><div class="page-intro"><div><div class="eyebrow">SYSTEM</div><h1>Configuración</h1><p>Preferencias de la experiencia.</p></div></div><div class="settings-list"><div class="setting"><div><b>Mercado</b><p>Actualización manual.</p></div><span class="chip">Manual</span></div><div class="setting"><div><b>Operación</b><p>Seguimiento periódico.</p></div><span class="chip">10 s</span></div><div class="setting"><div><b>Ejecución</b><p>Auto-Apply separado de pagos.</p></div><span class="chip">Seguro</span></div><div class="setting"><div><b>Interfaz</b><p>Responsive móvil/escritorio.</p></div><span class="chip">Activa</span></div></div></div>'};
function bindFilters(){const f=$('filters');if(f)f.onsubmit=e=>{e.preventDefault();S.page=1;refreshMarket()}}
function params(){const p=new URLSearchParams({page:S.page,take:'100',orderBy:$('fo')?.value||'updated_at',orderType:$('fd')?.value||'desc'});[['ft','type'],['fc','coin'],['fmin','min'],['fmax','max']].forEach(x=>{const v=$(x[0])?.value?.trim();if(v)p.set(x[1],v)});return p}
async function refreshMarket(){try{const p=await api('/api/p2p?'+params());S.offers=p.data||[];S.total=Number(p.total??S.offers.length);S.lastPage=Math.max(1,Math.ceil(S.total/Number(p.per_page||100)));nav();toast('Mercado sincronizado','success')}catch(e){toast(e.message,'error')}}
function drawOffers(){const b=$('offers');if(!b)return;b.innerHTML=S.offers.length?S.offers.map(o=>{const u=o.User||{},v=rate(o),id=String(o.uuid??o.id??'');return '<tr><td><span class="type '+esc(o.type)+'">'+esc(o.type)+'</span></td><td>'+esc(o.coin)+'</td><td class="strong">'+num(v,4)+'</td><td>'+num(o.amount)+'</td><td>'+num(o.receive)+'</td><td>'+num(o.available_amount)+'</td><td><b>'+esc(u.username||u.name||'—')+'</b><small>'+(u.kyc?'KYC':'—')+'</small></td><td>'+num(u.rating_avg)+'</td><td><button class="button primary compact" onclick="applyOffer(\''+esc(id)+'\')">Aplicar</button></td></tr>'}).join(''):'<tr><td colspan="9" class="empty-cell">No hay ofertas.</td></tr>'}
async function applyOffer(id){if(!confirm('Aplicar a esta oferta ahora?'))return;try{await api('/api/p2p/'+encodeURIComponent(id)+'/apply',{method:'POST'});S.active=id;localStorage.setItem('qvapay.activeOperationId',id);await loadOperation();toast('Aplicación aceptada por QvaPay','success')}catch(e){toast(e.message,'error')}}
async function loadOperation(){if(!S.active)return;try{const p=await api('/api/p2p/'+encodeURIComponent(S.active));S.operation=p?.qvapay?.p2p??p?.qvapay?.data??p?.qvapay??p?.data??p;if((location.hash.slice(1)||'/')==='/operations')nav()}catch(e){}}
function opCard(){const o=S.operation||{};return '<section class="card operation-live"><div class="operation-top"><div><span class="eyebrow">LIVE OPERATION</span><h2>'+esc(String(o.type||'P2P').toUpperCase())+' · '+esc(o.coin||'—')+'</h2></div><span class="status-chip">● '+esc(String(o.status||o.state||'PROCESSING').toUpperCase())+'</span></div><div class="operation-grid"><div><span>UUID</span><b>'+esc(S.active)+'</b></div><div><span>Monto</span><b>'+num(o.amount)+'</b></div><div><span>Recibe</span><b>'+num(o.receive)+'</b></div><div><span>Contraparte</span><b>'+esc(o.User?.username||o.user?.username||o.Peer?.username||'—')+'</b></div><div><span>Actualizado</span><b>'+time(o.updated_at||o.updatedAt)+'</b></div></div><div class="operation-actions"><button class="button secondary" onclick="loadOperation()">↻ Actualizar</button><a class="button ghost" href="#/market">Mercado</a></div></section>'}
function drawHome(){const e=$('miniOffers');if(e)e.innerHTML=S.offers.slice(0,6).map(o=>'<div class="mini-row"><span class="type '+esc(o.type)+'">'+esc(o.type)+'</span><b>'+esc(o.coin)+'</b><strong>'+num(rate(o),4)+'</strong><span>'+num(o.amount)+' QUSD</span></div>').join('')||'<div class="empty-inline">Sin datos.</div>'}
function drawBars(){const e=$('bars');if(!e)return;const a=S.offers.map(rate).filter(Number.isFinite).slice(0,12),m=Math.max(...a);e.innerHTML=a.length?a.map((v,i)=>'<div class="bar-row"><span>#'+(i+1)+'</span><div><i style="width:'+Math.max(5,v/m*100)+'%"></i></div><b>'+num(v,4)+'</b></div>').join(''):'<div class="empty-inline">Carga ofertas desde Mercado.</div>'}
function changePage(d){if(S.page+d<1||S.page+d>S.lastPage)return;S.page+=d;refreshMarket()}
async function loadAuto(){try{const a=await api('/api/auto-apply/config'),b=await api('/api/auto-apply/status');S.config=a.config;S.auto=b.status}catch(e){}}
function bindAuto(){const f=$('af');if(!f)return;$('at').value=S.config?.type||'sell';f.onsubmit=async e=>{e.preventDefault();const val=id=>$(id).value.trim()===''?null:Number($(id).value),en=$('ae').checked;if(en&&!S.config?.enabled&&!confirm('Activar Auto-Apply?'))return;try{await api('/api/auto-apply/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:en,type:$('at').value,coin:$('ac').value.trim().toUpperCase(),rateMin:val('arm'),rateMax:val('arx'),amountMin:val('aom'),amountMax:val('aox'),dailyMaxQusd:val('adl'),maxConcurrent:Number($('acon').value)})});await loadAuto();nav();toast('Reglas guardadas','success')}catch(e){toast(e.message,'error')}}}
async function loadMarket(){try{const p=await api('/api/p2p?page=1&take=100&orderBy=updated_at&orderType=desc');S.offers=p.data||[];S.total=Number(p.total??S.offers.length);S.lastPage=Math.max(1,Math.ceil(S.total/Number(p.per_page||100)))}catch(e){}}
async function refreshAll(){await Promise.all([loadMarket(),loadAuto(),loadOperation()]);nav();toast('Scanner sincronizado','success')}
window.refreshAll=refreshAll;window.refreshMarket=refreshMarket;window.changePage=changePage;window.applyOffer=applyOffer;window.loadOperation=loadOperation;
const commands=Object.entries(meta).map(([href,v])=>({href,label:v[1],group:v[0]}));
function renderCommands(q=''){const box=$('commandResults');if(!box)return;const list=commands.filter(x=>(x.label+' '+x.group).toLowerCase().includes(q.toLowerCase()));box.innerHTML=list.map((x,i)=>'<a class="command-item'+(i===0?' selected':'')+'" href="#'+x.href+'"><b>'+x.label+'</b><small>'+x.group+'</small></a>').join('')||'<div class="command-item">Sin resultados</div>'}
function openCommands(){const p=$('commandPalette');if(!p)return;p.classList.add('open');p.setAttribute('aria-hidden','false');$('commandInput').value='';renderCommands();setTimeout(()=>$('commandInput').focus(),20)}
function closeCommands(){const p=$('commandPalette');if(p){p.classList.remove('open');p.setAttribute('aria-hidden','true')}}
function setupCommands(){document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommands()}if(e.key==='Escape')closeCommands()});$('commandBackdrop')?.addEventListener('click',closeCommands);$('commandInput')?.addEventListener('input',e=>renderCommands(e.target.value));document.querySelector('.mobile-nav')?.addEventListener('click',closeCommands)}
window.openCommands=openCommands;
async function init(){document.getElementById('menuButton').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('mobileOverlay').onclick=()=>document.getElementById('sidebar').classList.remove('open');document.getElementById('refreshButton').onclick=refreshAll;document.getElementById('commandButton')?.addEventListener('click',openCommands);setupCommands();addEventListener('hashchange',nav);await Promise.all([loadMarket(),loadAuto(),loadOperation()]);nav();setInterval(loadAuto,5000);setInterval(()=>S.active&&loadOperation(),10000)}init();